### ISSUE TITLE
Deserializing Issue

### ISSUE THREAD

**Issue by Dassy23** [Blockdaemon/solana-accountsdb-plugin-kafka#19]
Currently running this plugin and producing to confluent cloud. But not able to deserialize correctly, is there anything in particular, besides the proto file, that is needed to deserialize?🙏🏼

**Comment by kpaddy** [comment]
> 

I am having similar issues. Any luck with deserializing the messages?

**Comment by terorie** [comment]
Hi @Dassy23 @kpaddy sorry for the delay. Confluent Cloud UI is not able to deserialize Protobuf messages, so this issue should be reported to Confluent instead. Kafka consumers (e.g. in Go) should be able to process messages fine. Please let me know if you think otherwise.
