### ISSUE TITLE
ci/rust-version.sh should use or match rust-version

### ISSUE THREAD

**Issue by nyetwurk** [Blockdaemon/solana-accountsdb-plugin-kafka#86]
Currently, both `rust-version` and `ci/rust-version.sh` have to be manually kept in sync. This makes no sense.

**Comment by LimKianAn** [comment]
@nyetwurk, you can assign that to me if you're not working on it.

**Comment by nyetwurk** [comment]
See also https://github.com/Blockdaemon/solana-accountsdb-plugin-kafka/pull/68
